### ISSUE TITLE
If ports are not available, bind to different ones

### ISSUE THREAD

**Issue by danthedaniel** [creesch/minecraft-web-chat#14]
I SIGKILL'd Minecraft and on relaunch :8081 was unavailable, but there was no fallback so the mod just didn't work.

**Comment by creesch** [comment]
That port was probably still bound due to you using SIGKILL or there is still a lingering process. For normal shutdown operations this should work better once my javalin PR is done.  

The proposed solution doesn't make sense to me as it is an issue of the port not being available.
