### ISSUE TITLE
Reorganize parsing/validation/escaping code

### ISSUE THREAD

**Issue by danthedaniel** [creesch/minecraft-web-chat#20]
* Validate component structure up front
* Use HTML elements instead of string templating

**Comment by danthedaniel** [comment]
@creesch I'm kinda stuck on figuring out the schema for the hoverEvent property of a component. I'm not finding any consistent format between the MC wiki, events from the websocket server, or old JSON schema files online. Any tips?

**Comment by creesch** [comment]
> @creesch I'm kinda stuck on figuring out the schema for the hoverEvent property of a component. I'm not finding any consistent format between the MC wiki, events from the websocket server, or old JSON schema files online. Any tips?

What I implemented is mostly from what I could see in messages coming by. You could have a look at how prismarine-chat handles these maybe?



Btw, I also didn't go for a complete implementation. Just in case you are wondering about click events I ignored most of those on purpose.

**Comment by creesch** [comment]
Fyi, as a heads up, I am going to do some refactoring around the websocket payload. This shouldn't affect any of the parsing but might influence things in chat.mjs a bit.

The biggest change is that I am going to wrap the Minecraft message JSON in a bigger JSON message to be able to add meta data and support other messages.
