### ISSUE TITLE
Error tracking

### ISSUE THREAD

**Issue by danthedaniel** [creesch/minecraft-web-chat#26]
Should we use some kind of error tracking (SaaS or home-built)? It would be nice to know for example if there's a problem with message parsing for some exotic use case.

**Comment by creesch** [comment]
Unless I am mistaken you are proposing we add telemetry to the mod. Which is a firm no for me.

**Comment by danthedaniel** [comment]
Okay. Self-hosted telemetry with limited data collection might avoid most issues. But I'll close this issue.
