### ISSUE TITLE
User ping and/or keyword based ping

### ISSUE THREAD

**Issue by creesch** [creesch/minecraft-web-chat#7]
title

**Comment by danthedaniel** [comment]
Perhaps with browser notification support?

**Comment by danthedaniel** [comment]
* There should be a mod menu configuration option to allow users to have a list of keywords. By default this is only the Minecraft username of the player
  * Might need a separate flag for the username as dynamically populating the list with different usernames is too complicated
* There should be a visual indication for the favicon when there is a ping
* There should be a visual indication for the messages that have pings
* Maybe:
  * Play a sound when there is a ping
  * Perform a system notification when there is a ping
* The server will boil down the ping into a boolean field in the `chatMessage` JSON object.

**Comment by creesch** [comment]
- Pings from history playback should have the visual indication on the message but otherwise be silent. 

> The server will boil down the ping into a boolean field in the `chatMessage` JSON object.

That one is the pure minecraft serialized chat message.  I was more thinking we add a `metaData` field [here\(https://github.com/creesch/minecraft-web-chat/blob/main/src/client/java/dev/creesch/model/WebsocketJsonMessage.java#L18) which can just be an object so it gives us some flexibility. 

I suppose we can also expand the model itself and properly define the `chatMessage` object, something like 

```
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    private static class ChatServerInfo {
        private JsonElement minecraftJsonPayload;
        private Object metaData;
    }
```

Which would work slightly better when calling the message parser class for styling pings.

**Comment by danthedaniel** [comment]
> Pings from history playback should have the visual indication on the message but otherwise be silent.

Maybe not so reasonable because we don't have a `MinecraftClient` instance to pull a username from. Unless we record if a message caused a ping in SQLite we can't have accurate historic ping information. Should we add that as a boolean column?

**Comment by creesch** [comment]
> > Pings from history playback should have the visual indication on the message but otherwise be silent.
> 
> Maybe not so reasonable because we don't have a `MinecraftClient` instance to pull a username from. Unless we record if a message caused a ping in SQLite we can't have accurate historic ping information. Should we add that as a boolean column?

Commenting here as well just so it doesn't get lost. A boolean column is probably best, no need for a schema change either as we didn't do a release.

**Comment by creesch** [comment]
@danthedaniel  something else I want to run by you. Earlier I suggested a Tildes special which would be a bit much to target specifically. 

But I just noticed that there is a `name` and `displayName` field available for `client.player`. I wasn't sure if they would be different as my tildes and minecraft name match. But accessing the same fields in a slightly different context I was able to test it against someone who does: 

```
[15:48:21] [Render thread/INFO]: [web-chat] playerName: gnawky, displayName: {"text":"chewonbananas","color":"#0099CC"}
```

I then also did a little bit of a test on a singleplayer world 

```java
String nameJSON = Text.Serialization.toJsonString(client.player.getName(), client.world.getRegistryManager());
LOGGER.info(nameJSON);
LOGGER.info(client.player.getDisplayName().getString());
String displayNameJson = Text.Serialization.toJsonString(client.player.getDisplayName(), client.world.getRegistryManager());
LOGGER.info(displayNameJson);
```

```
[16:37:10] [Render thread/INFO]: [web-chat] creesch
[16:37:10] [Render thread/INFO]: [web-chat] "creesch"
[16:37:10] [Render thread/INFO]: [web-chat] creesch
[16:37:10] [Render thread/INFO]: [web-chat] {"text":"creesch","hoverEvent":{"contents":{"type":"minecraft:player","id":[2097578677,-1517796232,-2140994661,-1953866359],"name":"creesch"},"action":"show_entity"},"insertion":"creesch","clickEvent":{"action":"suggest_command","value":"/tell creesch "}}
```

So, using  `displayName.getString()` works pretty neatly to get the name from the player as they are seen by others. 


So, what I am thinking is that if the "ping on username" toggle is on we simply target both. That makes it work on any server where usernames might be changed just like on tildes.
